#!/bin/sh
address="$(ip -4 route get 1.1.1.1 | sed -n 's/.* src \([^ ]*\).*/\1/p')"

if [ -z "$address" ]; then
  echo "Could not determine the primary IPv4 address" >&2
  exit 1
fi

exec /usr/bin/avahi-publish-address -R black-hole-explorer.local "$address"
